# Generated by Django 4.1.1 on 2022-09-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_req', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='resuests',
            name='login',
        ),
        migrations.AddField(
            model_name='resuests',
            name='type_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='support.types_request'),
            preserve_default=False,
        ),
    ]
