# Generated by Django 4.1.1 on 2022-09-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_types_request_remove_resuests_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resuests',
            options={'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='resuests',
            name='body',
            field=models.TextField(verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='resuests',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='resuests',
            name='type_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.types_request', verbose_name='Тип заявки'),
        ),
    ]
