# Generated by Django 4.1.1 on 2022-09-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_resuests_options_alter_resuests_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resuests',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
