# Generated by Django 4.1.3 on 2022-12-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='admin_message',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_request',
        ),
        migrations.AddField(
            model_name='answer',
            name='request_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='support.resuests'),
            preserve_default=False,
        ),
    ]
